dhaka/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('google.urls')),
    path('',include('youtube.urls')),
]

google/urls.py
from google import views
from django.urls import path
urlpatterns = [
    path('', views.home,name='home'),
    path('url/',views.url_info,name='url'),
    path('info/',views.user_info,name='info'),
    path('form/',views.formtest,name='form'),
]

youtube/urls.py
from youtube import views
from django.urls import path

app_name='youtube'
urlpatterns = [
    path('index/', views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('other/',views.other,name='other'),

]

google/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    topic_name=models.CharField(max_length=200,unique=True)

    def __str__(self):
        return self.topic_name


class Webpage(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    name=models.CharField(max_length=200,unique=True)
    url=models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name=models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date=models.DateField()

    def __str__(self):
        return str(self.date)


class user(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email=models.EmailField(unique=True)


    def __str__(self):
        return self.first_name

youtube/models.py
from django.db import models

# Create your models here.

google/forms.py
from django import forms
from .models import *
from django.core import validators


def look_for_z(value):
    if value[0].lower() !='z':
        raise  forms.ValidationError("Must start with 'z")

class FirstForm(forms.Form):
    name=forms.CharField(validators=[look_for_z,validators.validate_slug])
    email=forms.EmailField()
    verify_email=forms.EmailField()
    body=forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0,message="GOTCHA BOT!")])

    #def clean_botcatcher(self):
        #botcatcher = self.cleaned_data['botcatcher']
        #if len(botcatcher) > 0:
            #raise forms.ValidationError("Gotcha BOT")
        #return botcatcher
    def clean(self):
        all_cleaned_data=super().clean()

        email=all_cleaned_data['email']
        verify_email=all_cleaned_data['verify_email']

        if email[email.find('@')+1:email.find('@')+6] != 'gmail':
            raise forms.ValidationError("eamil domain must be gamil")

        if email != verify_email:
            raise forms.ValidationError("email and verify email is not match!.")

google/views.py
from django.shortcuts import render
from .models import *
from .forms import FirstForm
# Create your views here.

def home(request):
    context={

    }
    return render(request,'home.html',context)


def url_info(request):
    webpg=AccessRecord.objects.order_by('date')

    context={
        "a_r":webpg
    }

    return render(request,'url_info.html',context)


def user_info(request):
    info=user.objects.all()
    context={
        "user":info
    }
    return render(request,'user_info.html',context)









def formtest(request):
    form=FirstForm()
    if request.method=='POST':
        form=FirstForm(request.POST)
        if form.is_valid():

            name=form.cleaned_data['name']
            email=form.cleaned_data['email']
            body=form.cleaned_data['body']

            context={
                "c_name":name,
                "c_email":email,
                "c_body":body,
            }

            return render(request,'success.html',context)

    context={
        "form":form,
    }
    return render(request,'from.html',context)

youtube/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context={
        "insert":"hello dhaka",
        "insert_num":100,
    }
    return render(request,'index.html',context)

def contact(request):
    return render(request,'contact.html')

def other(request):
    return render(request,'other.html')

templates/base.html
<!doctype html>
<html lang="en" class="h-100" xmlns="http://www.w3.org/1999/html">
  <head>
      {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title> {% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      footer{

        background:black;

      }
    </style>
    <!-- Custom styles for this template -->
    <link href="sticky-footer-navbar.css" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100">
    <header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'youtube:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'youtube:contact' %}">Contact<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'youtube:other' %}">Other</a>
        </li>

          <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>

      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">

     <h1 class="mt-5">
          {% block container %}

      {% endblock %}
     </h1>


</main>

<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Hello imran hossain this is footer section.</span>
       <span class="text-muted">Hello imran hossain this is footer section.</span>
       <span class="text-muted">Hello imran hossain this is footer section.</span>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  </body>


</html>

templates/from.html
{% extends 'home.html' %}
{% load static %}

{% block container %}

    <h1>Fill out Forms</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

templates/home.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>home</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/navbar-fixed/">
      <link rel="stylesheet" href="{% static 'css/Mystyle.css' %}">

    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/navbar-fixed/navbar-top-fixed.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Fixed navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


    <div class="container">

        {% block container %}


        {% endblock %}
    </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script></body>
</html>

templates/success.html
{% extends 'home.html' %}
{% load static %}

{% block container %}

    <h1>success</h1>
    <p>Name :{{c_name}}</p>
    <p>E-mail :{{c_email}}</p>
    <p>Body :{{c_body}}</p>

{% endblock %}

templates/url_info.html
{% extends 'home.html' %}

{% load static %}

{% block container %}

    <h1>URL Name and Last Access Date</h1>
    {% if a_r %}
        <table>
            <thead>
                <th>Site Name</th>
                <th>Access Date</th>
            </thead>
            {% for a in a_r %}

                <tr>
                    <td>{{a.name}}</td>
                    <td>{{a.date}}</td>
                </tr>
            {% endfor %}

            {% else %}
            <p>No Data Found</p>
    {% endif %}

{% endblock %}

templates/user_info.html
{% extends 'home.html' %}

{% block container %}
    {% if user %}
        <table class="table table-dark">
  <thead>
    <tr>

      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">E-mail</th>
    </tr>
  </thead>
  <tbody>
  {% for u in user %}
    <tr>

      <td>{{u.first_name}}</td>
      <td>{{u.last_name}}</td>
      <td>{{u.email}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    {% else %}
        <p>No Data Found</p>
    {% endif %}
{% endblock %}

youtube/templates/contact.html
{% extends 'base.html' %}

{% block title %}
   contact
{% endblock %}

{% block container %}
    <h1>this is our contact page</h1>
{% endblock %}

youtube/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load myextras %}

{% block title %}
    home
{% endblock %}

{% block container %}
    <div class="container">
        <h1>this is home page</h1>
        {{ insert|upper }}<br>

        {{insert|mysupercut:"h"}}<br>

        {{insert|addstring:"imran"}}<br>

        {{ insert_num|add:"99" }}
    </div>
{% endblock %}

youtube/templates/other.html
{% extends 'base.html' %}

{% block title %}
    other
{% endblock %}

{% block container %}
    <h1>this is our other page</h1>
{% endblock %}